version: '3'

services:
  database:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=kysely_usr
      - POSTGRES_PASSWORD=kysely_pwd
      - POSTGRES_DB=chat-app